[package]
name = "tera-cli"
version = "0.2.1"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]
description = "Tera CLI for one-off template interpolation from context file / env vars"
edition = "2018"
readme = "README.md"
categories = ["command-line-utilities", "value-formatting"]
license = "MIT"

[dependencies]
tera = "0.11.20"
structopt = "0.2.18"
serde = "1.0.99"
toml = "0.5.3"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
snafu = "0.5.0"

[[bin]]
name = "tera"
path = "src/main.rs"
