[package]
name = "tera-cli"
version = "0.1.1"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]
description = "Tera CLI for one-off template interpolation from context file / env vars"
edition = "2018"
readme = "README.md"
categories = ["command-line-utilities", "value-formatting"]
license = "MIT"

[dependencies]
tera = "0.11.20"
structopt = "0.2.15"
serde = "1.0.90"
toml = "0.5.0"
serde_json = "1.0.39"

[[bin]]
name = "tera"
path = "src/main.rs"
