[package]
name = "tera-cli"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]
edition = "2018"

[dependencies]
tera = "0.11.20"
structopt = "0.2.15"
failure = "0.1.5"
serde = "1.0.90"
toml = "0.5.0"
serde_json = "1.0.39"

[[bin]]
name = "tera"
path = "src/main.rs"
